# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sundap.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(371, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(371, 600))
        MainWindow.setMaximumSize(QtCore.QSize(371, 600))
        MainWindow.setStyleSheet("#centralwidget{\n"
"     background-color: #041f1a;\n"
"}\n"
"\n"
"#album_art {\n"
"    border-image:url(:/album/album_art.png);\n"
"}\n"
"\n"
"#title_label{\n"
"    margin: 0 5 0 0;\n"
"}\n"
"\n"
"#playbar_slider::groove:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494318, x2:1, y2:0.489, stop:0 rgba(23, 197, 170, 255), stop:0.784091 rgba(23, 197, 109, 255));\n"
"    border: none;\n"
"    height: 40px;\n"
"    margin: 0px;\n"
"}\n"
"#playbar_slider::handle:horizontal {\n"
"    background-color: #17c56d;\n"
"    border: none;\n"
"    height: 40px;\n"
"    width: 10px;\n"
"    margin: -15px 0px;\n"
"}\n"
"#playbar_slider::sub-page:horizontal{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494318, x2:1, y2:0.489, stop:0 rgba(23, 197, 170, 255), stop:0.784091 rgba(23, 197, 109, 255));\n"
"}\n"
"#playbar_slider::add-page:horizontal{\n"
"    background: #0a463a;\n"
"}\n"
"\n"
"\n"
"#button_play{\n"
"    border-image: url(:/normal/play.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"#button_play::hover{\n"
"    border-image: url(:/hover/play_hover.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"#button_play::pressed {\n"
"    border-image: url(:/press/play_press.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"\n"
"#button_next{\n"
"    border-image: url(:/normal/next.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"#button_next::hover{\n"
"    border-image: url(:/hover/next_hover.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"#button_next::pressed {\n"
"    border-image: url(:/press/next_press.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"\n"
"#button_prev{\n"
"    border-image: url(:/normal/prev.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"#button_prev::hover{\n"
"    border-image: url(:/hover/prev_hover.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"#button_prev::pressed {\n"
"    border-image: url(:/press/prev_press.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.album_art = QtWidgets.QLabel(self.centralwidget)
        self.album_art.setMinimumSize(QtCore.QSize(353, 353))
        self.album_art.setMaximumSize(QtCore.QSize(353, 353))
        self.album_art.setText("")
        self.album_art.setScaledContents(False)
        self.album_art.setAlignment(QtCore.Qt.AlignCenter)
        self.album_art.setWordWrap(False)
        self.album_art.setOpenExternalLinks(False)
        self.album_art.setObjectName("album_art")
        self.verticalLayout_2.addWidget(self.album_art)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.playbar_current = QtWidgets.QLabel(self.centralwidget)
        self.playbar_current.setMaximumSize(QtCore.QSize(16777215, 15))
        self.playbar_current.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.playbar_current.setObjectName("playbar_current")
        self.gridLayout_2.addWidget(self.playbar_current, 0, 0, 1, 1)
        self.playbar_length = QtWidgets.QLabel(self.centralwidget)
        self.playbar_length.setMaximumSize(QtCore.QSize(16777215, 15))
        self.playbar_length.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.playbar_length.setObjectName("playbar_length")
        self.gridLayout_2.addWidget(self.playbar_length, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.playbar_slider = QtWidgets.QSlider(self.centralwidget)
        self.playbar_slider.setOrientation(QtCore.Qt.Horizontal)
        self.playbar_slider.setObjectName("playbar_slider")
        self.gridLayout.addWidget(self.playbar_slider, 2, 0, 1, 1)
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_prev = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_prev.sizePolicy().hasHeightForWidth())
        self.button_prev.setSizePolicy(sizePolicy)
        self.button_prev.setMinimumSize(QtCore.QSize(81, 81))
        self.button_prev.setText("")
        self.button_prev.setFlat(False)
        self.button_prev.setObjectName("button_prev")
        self.horizontalLayout.addWidget(self.button_prev)
        self.button_play = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_play.sizePolicy().hasHeightForWidth())
        self.button_play.setSizePolicy(sizePolicy)
        self.button_play.setMinimumSize(QtCore.QSize(128, 128))
        self.button_play.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_play.setIcon(icon)
        self.button_play.setIconSize(QtCore.QSize(128, 128))
        self.button_play.setCheckable(False)
        self.button_play.setFlat(True)
        self.button_play.setObjectName("button_play")
        self.horizontalLayout.addWidget(self.button_play)
        self.button_next = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_next.sizePolicy().hasHeightForWidth())
        self.button_next.setSizePolicy(sizePolicy)
        self.button_next.setMinimumSize(QtCore.QSize(81, 81))
        self.button_next.setText("")
        self.button_next.setFlat(False)
        self.button_next.setObjectName("button_next")
        self.horizontalLayout.addWidget(self.button_next)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action_open_folder = QtWidgets.QAction(MainWindow)
        self.action_open_folder.setObjectName("action_open_folder")
        self.menu.addAction(self.action_open_folder)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playbar_current.setText(_translate("MainWindow", "0:00"))
        self.playbar_length.setText(_translate("MainWindow", "-:--"))
        self.title_label.setText(_translate("MainWindow", "Artist - Title"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.action_open_folder.setText(_translate("MainWindow", "Открыть папку"))

from ui.assets import resources
